services:
  backend:
    build: ./backend
    container_name: weather-backend
    ports:
      - "3001:3000"
    networks:
      - weather-net
  frontend:
    build: ./frontend
    container_name: weather-frontend
    ports:
      - "8888:80"
    depends_on:
      - backend
    networks:
      - weather-net
networks:
  weather-net:
