services:
  backend:
    build:
      context: "https://github.com/iireddrag0nii/weather-dashboard.git#main:backend"
    container_name: weather-backend
    ports:
      - "3001:3000"
    networks:
      - weather-net
  frontend:
    build:
      context: "https://github.com/iireddrag0nii/weather-dashboard.git#main:frontend"
    container_name: weather-frontend
    ports:
      - "8888:80"
    depends_on:
      - backend
    networks:
      - weather-net
networks:
  weather-net: